<?php
// ==========================================================================
// DIBANGKITKAN OTOMATIS — JANGAN DISUNTING MANUAL
// Sumber : assets/js/rbac.js
// Perintah: node db/gen-rbac.js
// --------------------------------------------------------------------------
// Inilah batas keamanan yang sesungguhnya. Pemeriksaan hak akses di sisi
// peramban hanya mengatur tampilan; setiap permintaan API diperiksa di sini.
// ==========================================================================

const RBAC_MODULES = [
  'dashboard',
  'master-data',
  'bmn-register',
  'asset-lifecycle',
  'qr-tag',
  'sensus',
  'mutasi',
  'custodian',
  'jml',
  'maintenance',
  'inspection',
  'iot',
  'risk',
  'performance',
  'financial',
  'reconciliation',
  'disposal',
  'cyber',
  'sanitization',
  'governance',
  'audit',
  'documents',
  'reporting',
  'integrasi',
  'approval',
  'access',
  'users',
];

const ROLE_ACCESS = [
  'Super Admin' => [
    'dashboard' => 'R',
    'master-data' => 'RW',
    'bmn-register' => 'RW',
    'asset-lifecycle' => 'RW',
    'qr-tag' => 'RW',
    'sensus' => 'RW',
    'mutasi' => 'RW',
    'custodian' => 'RW',
    'jml' => 'RW',
    'maintenance' => 'RW',
    'inspection' => 'RW',
    'iot' => 'RW',
    'risk' => 'RW',
    'performance' => 'RW',
    'financial' => 'RW',
    'reconciliation' => 'RW',
    'disposal' => 'RW',
    'cyber' => 'RW',
    'sanitization' => 'RW',
    'governance' => 'RW',
    'audit' => 'RW',
    'documents' => 'RW',
    'reporting' => 'RW',
    'integrasi' => 'RW',
    'approval' => 'R',
    'access' => 'R',
    'users' => 'RW',
  ],
  'Asset Manager' => [
    'dashboard' => 'R',
    'master-data' => 'R',
    'bmn-register' => 'RW',
    'asset-lifecycle' => 'RW',
    'qr-tag' => 'R',
    'sensus' => 'A',
    'mutasi' => 'A',
    'custodian' => 'RW',
    'jml' => 'R',
    'maintenance' => 'A',
    'inspection' => 'R',
    'iot' => 'RW',
    'risk' => 'RW',
    'performance' => 'RW',
    'financial' => 'R',
    'reconciliation' => 'A',
    'disposal' => 'RW',
    'cyber' => 'A',
    'sanitization' => 'A',
    'governance' => 'RW',
    'audit' => 'R',
    'documents' => 'RW',
    'reporting' => 'R',
    'integrasi' => 'R',
    'approval' => 'A',
    'access' => 'R',
  ],
  'BMN Officer' => [
    'dashboard' => 'R',
    'master-data' => 'R',
    'bmn-register' => 'RW',
    'asset-lifecycle' => 'R',
    'qr-tag' => 'RW',
    'sensus' => 'RW',
    'mutasi' => 'RW',
    'custodian' => 'RW',
    'jml' => 'RW',
    'maintenance' => 'R',
    'inspection' => 'R',
    'risk' => 'R',
    'performance' => 'R',
    'financial' => 'R',
    'reconciliation' => 'RW',
    'disposal' => 'RW',
    'cyber' => 'R',
    'sanitization' => 'R',
    'governance' => 'R',
    'audit' => 'R',
    'documents' => 'RW',
    'reporting' => 'R',
    'integrasi' => 'R',
    'approval' => 'R',
    'access' => 'R',
  ],
  'Finance' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'asset-lifecycle' => 'R',
    'performance' => 'R',
    'financial' => 'RW',
    'reconciliation' => 'R',
    'disposal' => 'R',
    'audit' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'access' => 'R',
  ],
  'Maintenance' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'qr-tag' => 'R',
    'maintenance' => 'RW',
    'inspection' => 'R',
    'iot' => 'RW',
    'risk' => 'R',
    'performance' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'access' => 'R',
  ],
  'Inspector' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'qr-tag' => 'R',
    'sensus' => 'RW',
    'maintenance' => 'R',
    'inspection' => 'RW',
    'iot' => 'R',
    'performance' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'access' => 'R',
  ],
  'Custodian' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'qr-tag' => 'R',
    'mutasi' => 'RW',
    'custodian' => 'R',
    'jml' => 'RW',
    'maintenance' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'access' => 'R',
  ],
  'Cyber Officer' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'iot' => 'RW',
    'risk' => 'RW',
    'disposal' => 'A',
    'cyber' => 'RW',
    'sanitization' => 'RW',
    'governance' => 'R',
    'audit' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'integrasi' => 'R',
    'approval' => 'A',
    'access' => 'R',
  ],
  'Auditor' => [
    'dashboard' => 'R',
    'master-data' => 'R',
    'bmn-register' => 'R',
    'asset-lifecycle' => 'R',
    'qr-tag' => 'R',
    'sensus' => 'R',
    'mutasi' => 'R',
    'custodian' => 'R',
    'jml' => 'R',
    'maintenance' => 'R',
    'inspection' => 'R',
    'iot' => 'R',
    'risk' => 'R',
    'performance' => 'R',
    'financial' => 'R',
    'reconciliation' => 'R',
    'disposal' => 'R',
    'cyber' => 'R',
    'sanitization' => 'R',
    'governance' => 'R',
    'audit' => 'R',
    'documents' => 'R',
    'reporting' => 'R',
    'integrasi' => 'R',
    'approval' => 'R',
    'access' => 'R',
    'users' => 'R',
  ],
  'Management' => [
    'dashboard' => 'R',
    'bmn-register' => 'R',
    'iot' => 'R',
    'risk' => 'A',
    'performance' => 'R',
    'financial' => 'R',
    'reconciliation' => 'A',
    'disposal' => 'A',
    'sanitization' => 'A',
    'governance' => 'R',
    'audit' => 'R',
    'reporting' => 'R',
    'integrasi' => 'R',
    'approval' => 'A',
    'access' => 'R',
    'users' => 'R',
  ],
];

const ROLE_DESC = [
  'Super Admin' => 'Konfigurasi teknis sistem, master data dan integrasi. Tidak otomatis berwenang menyetujui transaksi operasional.',
  'Asset Manager' => 'Pemilik proses siklus hidup aset: kondisi, risiko, kinerja dan keputusan lifecycle. Menyetujui sensus, mutasi, maintenance, rekonsiliasi dan sanitisasi.',
  'BMN Officer' => 'Penatausahaan BMN: register, tagging QR/barcode, sensus, mutasi dan rekonsiliasi SAKTI/SIMAN.',
  'Finance' => 'Biaya dan nilai aset sesuai kewenangan: lifecycle cost, TCO, dan referensi nilai perolehan.',
  'Maintenance' => 'Pemeliharaan preventif/korektif, work order, dan tindak lanjut alarm telemetry IoT.',
  'Inspector' => 'Inspeksi dan penilaian kondisi aset, serta pelaksanaan sensus lapangan.',
  'Custodian' => 'Aset yang menjadi tanggung jawabnya: acknowledgement, permintaan mutasi, dan pengembalian aset.',
  'Cyber Officer' => 'Aset siber/kripto sensitif, sanitisasi media, dan otorisasi keamanan pada proses disposal.',
  'Auditor' => 'Akses baca pada seluruh modul untuk keperluan pemeriksaan dan pengumpulan evidence. Tidak dapat mengubah data.',
  'Management' => 'Dashboard eksekutif, laporan, dan persetujuan pada risiko, rekonsiliasi, sanitisasi dan disposal.',
];
